name: CI
on:
  push:
    branches    : master
jobs:
  build:
    runs-on     : self-hosted
    steps:
      - name    : chekout repository
        uses    : actions/checkout@v2
      - name    : Setup node for npm
        uses    : actions/setup-node@master
        with:
          node-verison: '12.x'

      - name    : remove old build
        run     : rm -rf /home/nychvadim/actions-runner/_work/pcb_app/pcb_app/build
      - name    : Build npm
        run     : npm run build
  deployment: 
      name    : Deployment
      needs   : build
      runs-on : self-hosted
      steps   :
        - name    : Deploy files to nginx
          run     : |
              sudo rm -rf /var/html/denchik/sutdy/*
              sudo mv /home/nychvadim/actions-runner/_work/pcb_app/pcb_app/build/* /var/html/denchik/sutdy/ 
      
